
package com.example.consumingwebservice.wsdl.kps;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BilesikKutukSorgulaKimlikNoServis", targetNamespace = "http://kps.nvi.gov.tr/2021/04/01")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BilesikKutukSorgulaKimlikNoServis {


    /**
     * 
     * @param kriterListesi
     * @return
     *     returns com.example.consumingwebservice.wsdl.kps.BilesikKutukBilgileriSonucu
     */
    @WebMethod(operationName = "Sorgula", action = "http://kps.nvi.gov.tr/2021/04/01/BilesikKutukSorgulaKimlikNoServis/Sorgula")
    @WebResult(name = "SorgulaResult", targetNamespace = "http://kps.nvi.gov.tr/2021/04/01")
    @RequestWrapper(localName = "Sorgula", targetNamespace = "http://kps.nvi.gov.tr/2021/04/01", className = "com.example.consumingwebservice.wsdl.kps.Sorgula")
    @ResponseWrapper(localName = "SorgulaResponse", targetNamespace = "http://kps.nvi.gov.tr/2021/04/01", className = "com.example.consumingwebservice.wsdl.kps.SorgulaResponse")
    public BilesikKutukBilgileriSonucu sorgula(
        @WebParam(name = "kriterListesi", targetNamespace = "http://kps.nvi.gov.tr/2021/04/01")
        ArrayOfBilesikKutukSorgulaKimlikNoSorguKriteri kriterListesi);

}
